### ISSUE TITLE
"Hyper-V was unable to find a virtual machine with name"

### ISSUE THREAD

**Issue by BigNoseSec** [ananace/foreman_hyperv#16]
Hello All,

After setting up my HyperV box as a compute resc. in foreman, I see that I am now getting this error at seemingly random points in the host creation process (in the WebUI).

`Oops, we're sorry but something went wrong Hyper-V was unable to find a virtual machine with name "foreman_1515980741".
`

I have not yet provisioned anything to this hyperV Instance, nor do I have any VM with this name already on that hyperv box. 

 Would love some feedback on this issue!!

**Comment by ace13** [comment]
The "foreman_<numbers>" name is what Foreman uses when creating the objects necessary to provision the VM, the fact that the error message refers to it by that name means the error happens before the first provisioning call to Hyper-V.

Perhaps related to #8?

I can tag up and push a new version that incorporates the fix for said issue.

**Comment by BigNoseSec** [comment]
Looks to work now with the fix, thank you! :+1:

**Comment by ananace** [comment]
:tada:
